<?php

/** @var Magebit\PageListWidget\Block\Widget\PageList $block */
?>
<div class="widget block block-cms-link">
    <h3>
        <?= $block->escapeHtml($block->getData('cms_list_title')); ?>
    </h3>
    <ul>
    <?php foreach ($block->getPageList() as $page): ?>
        <li>
            <a href="<?= $block->escapeHtmlAttr($page->getIdentifier()) ?>" title="<?= $block->escapeHtmlAttr($page->getTitle()) ?>" >
            <span>
                <?= $block->escapeHtml($page->getTitle()) ?>
            </span>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
